package threshsig;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SignatureException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import static threshsig.ThreshUtil.FOUR;
import static threshsig.ThreshUtil.TWO;

/**
 * A GroupKey with information common to all the keyshares. Generated by the
 * Dealer class
 * 
 * Reference: "Practical Threshold Signatures",<br>
 * Victor Shoup (sho@zurich.ibm.com), IBM Research Paper RZ3121, 4/30/99<BR>
 * 
 * @author Steve Weis <sweis@mit.edu>
 */

// TODO: Investigate the security of reusing the key parameters (q,p) with a
// new Poly, since they are computationally expensive
public class GroupKey {
  /** (k,l) Parameters. k out of l shares needed for a signature */
  private int k, l;

  /** The exponent of the groupKeyPair */
  private BigInteger e;

  /** The RSA modulus of the groupKeyPair */
  private BigInteger n;

  /** Group Verifier */
  private BigInteger v;

  /** Verifier for each share */
  private BigInteger[] vk;

  private BigInteger delta;
  BigInteger eprime;

  public GroupKey(final int k, final int l,
      final BigInteger e, final BigInteger n, final BigInteger v, final BigInteger[] vk) {
    this.k = k;
    this.l = l;
    this.e = e;
    this.n = n;
    this.v = v;
    this.vk = vk;
    this.delta = ThreshUtil.factorial(l);
    // eprime = delta^2*4
    this.eprime = delta.multiply(delta).shiftLeft(2);
  }

  /**
   * Returns the minimum threshold size
   * 
   * @return The minimum threshold size for this group 'k'.
   */
  public int getK() {
    return k;
  }

  /**
   * Returns the group size
   * 
   * @return The size of this key's associated group.
   */
  public int getL() {
    return l;
  }

  /**
   * Returns the group key modulus
   * 
   * @return This group's modulus.
   */
  public BigInteger getModulus() {
    return n;
  }

  /**
   * Returns the group key exponent
   * 
   * @return This group's exponent
   */
  public BigInteger getExponent() {
    return e;
  }

  public BigInteger getGroupVerifier() {
    return v;
  }

  public BigInteger getVerifier(int id) {
    return vk[id - 1];
  }

  public BigInteger getDelta() {
    return delta;
  }

  // public Verification checkSignatures(final byte[] data, final SigShare[] sigs)
  // throws ThresholdSigException {
  // Verification verification = new Verification(data, sigs);
  // verification.checkSignatures();
  // return verification;
  // }

  public boolean verify(final byte[] data, final SigShare[] sigs) {
    final BigInteger x = (new BigInteger(data)).mod(n);
    return verify(data, sigs, x);
  }

  private boolean verify(final byte[] data, final SigShare[] sigs, BigInteger x) {
    BigInteger w = ThreshUtil.ONE;

    for (int i = 0; i < k; i++) {
      w = w.multiply(sigs[i].getSig().modPow(ThreshUtil.lambda(sigs[i].getId(), sigs, delta), n));
    }

    w = w.mod(n);
    final BigInteger xeprime = x.modPow(eprime, n);
    final BigInteger we = w.modPow(e, n);
    return (xeprime.compareTo(we) == 0);
  }

  public boolean verify(final byte[] data, final BigInteger signature) {
    final BigInteger x = (new BigInteger(data)).mod(n);

    final BigInteger xeprime = x.modPow(eprime, n);
    final BigInteger we = signature.modPow(e, n);
    return (xeprime.compareTo(we) == 0);
  }

  public boolean checkSigShare(final byte[] data, final SigShare sigShare) throws NoSuchAlgorithmException {
    return checkSigShare((new BigInteger(data)).mod(n).modPow(FOUR.multiply(delta), n), sigShare);
  }

  public boolean checkSigShare(final BigInteger xtilde, final SigShare sigShare) throws NoSuchAlgorithmException {
    final MessageDigest md = MessageDigest.getInstance(ThreshUtil.DIGEST_ALGO);

    final Verifier ver = sigShare.getSigVerifier();
    final BigInteger v = getGroupVerifier();
    final BigInteger vi = getVerifier(sigShare.getId());

    // debug("v :" + v);
    md.update(v.toByteArray());

    // debug("xtilde :" + xtilde);
    md.update(xtilde.toByteArray());

    // debug("vi :" + vi);
    md.update(vi.toByteArray());

    final BigInteger xi = sigShare.getSig();
    // debug("xi^2 :" + xi.modPow(TWO,n));
    md.update(xi.modPow(TWO, n).toByteArray());

    final BigInteger vz = v.modPow(ver.getZ(), n);

    final BigInteger vinegc = vi.modPow(ver.getC(), n).modInverse(n);
    // debug("v^z*v^-c :" + vz.multiply(vinegc).mod(n));
    md.update(vz.multiply(vinegc).mod(n).toByteArray());

    final BigInteger xtildez = xtilde.modPow(ver.getZ(), n);

    // TODO: CHECK PAPER!
    final BigInteger xineg2c = xi.modPow(ver.getC(), n).modInverse(n);
    // According to Shoup, pg. 8 this should be:
    // xi.modPow(TWO,n).modPow(ver.getC(),n).modInverse(n);

    // Something to do with working in Q_n since every
    // element is a square

    // debug("xi^-2cx: " + xineg2c.multiply(xtildez).mod(n));
    md.update(xineg2c.multiply(xtildez).mod(n).toByteArray());
    final BigInteger result = new BigInteger(md.digest()).mod(n);

    if (!result.equals(ver.getC())) {
      debug("Share verifier " + sigShare.getId() + " is not OK");
      return false;
    }
    return true;
  }

  public Aggregator starAggregation(byte[] data) {
    return new Aggregator(data);
  }

  // Debugging
  // ............................................................................
  private static void debug(final String s) {
    if (ThreshUtil.DEBUG)
      System.err.println("GroupKey: " + s);
  }

  public class Aggregator {
    final private byte[] data;
    final private List<SigShare> sigs;
    final BigInteger x;
    final BigInteger xtilde;
    private List<SigShare> failedSigs;
    final boolean[] haveSig;

    // private boolean valid = false;
    // private boolean verifiedRun = false;

    private Aggregator(byte[] signedData) {
      this.data = signedData;
      this.sigs = new ArrayList<>(getK());
      this.x = (new BigInteger(signedData)).mod(n);
      this.xtilde = x.modPow(FOUR.multiply(delta), n);
      this.failedSigs = new ArrayList<>();
      haveSig = new boolean[l];
    }

    public void tryAddSigShares(SigShare... sigShares) {
      for (SigShare sigShare : sigShares) {
        tryAddSigShare(sigShare);
      }
    }

    /**
     * Adds a sigShare to aggregated if it is valid and we still need more
     * signatures.
     * 
     * @param sigShare to be added
     * @return true if sigShare was added
     * @throws NullPointerException  if sigShare is null
     * @throws ThresholdSigException if signature has invalid id or share with same
     *                               id is already in aggregator.
     */
    public boolean tryAddSigShare(SigShare sigShare) {
      Objects.requireNonNull(sigShare);
      if (haveSig[sigShare.getId() - 1]) {
        throw new ThresholdSigException("Duplicate signature: " + sigShare.getId());
      }
      if (sigShare.getId() <= 0 || sigShare.getId() > getL()) {
        throw new ThresholdSigException("Signature id expected to be between 1 and " + getL() + " but is: " + sigShare);
      }

      if (sigs.size() >= getK()) {
        // Don't add if we already have enough sigs
        return false;
      }

      MessageDigest md;
      try {
        md = MessageDigest.getInstance(ThreshUtil.DIGEST_ALGO);
      } catch (NoSuchAlgorithmException e) {
        throw new RuntimeException(e);
      }

      final Verifier ver = sigShare.getSigVerifier();
      final BigInteger v = getGroupVerifier();
      final BigInteger vi = getVerifier(sigShare.getId());

      // debug("v :" + v);
      md.update(v.toByteArray());

      // debug("xtilde :" + xtilde);
      md.update(xtilde.toByteArray());

      // debug("vi :" + vi);
      md.update(vi.toByteArray());

      final BigInteger xi = sigShare.getSig();
      // debug("xi^2 :" + xi.modPow(TWO,n));
      md.update(xi.modPow(TWO, n).toByteArray());

      final BigInteger vz = v.modPow(ver.getZ(), n);

      final BigInteger vinegc = vi.modPow(ver.getC(), n).modInverse(n);
      // debug("v^z*v^-c :" + vz.multiply(vinegc).mod(n));
      md.update(vz.multiply(vinegc).mod(n).toByteArray());

      final BigInteger xtildez = xtilde.modPow(ver.getZ(), n);

      // TODO: CHECK PAPER!
      final BigInteger xineg2c = xi.modPow(ver.getC(), n).modInverse(n);
      // According to Shoup, pg. 8 this should be:
      // xi.modPow(TWO,n).modPow(ver.getC(),n).modInverse(n);

      // Something to do with working in Q_n since every
      // element is a square

      // debug("xi^-2cx: " + xineg2c.multiply(xtildez).mod(n));
      md.update(xineg2c.multiply(xtildez).mod(n).toByteArray());
      final BigInteger result = new BigInteger(md.digest()).mod(n);

      if (!result.equals(ver.getC())) {
        debug("Share verifier " + sigShare.getId() + " is not OK");
        failedSigs.add(sigShare);
        return false;
      }
      haveSig[sigShare.getId() - 1] = true;
      sigs.add(sigShare);
      return true;
    }

    public boolean verify() {
      if (sigs.size() != getK()) {
        throw new ThresholdSigException("Needed " + getK() + " signatures, but have: " + sigs.size());
      }
      return GroupKey.this.verify(data, sigs.toArray(new SigShare[getK()]), x);
    }

    public List<SigShare> getFailedSigs() {
      return failedSigs;
    }

    public BigInteger getSignature() {
      BigInteger w = ThreshUtil.ONE;

      if (sigs.size() != getK()) {
        throw new ThresholdSigException("Needed " + getK() + " signatures, but have: " + sigs.size());
      }

      for (int i = 0; i < k; i++) {
        w = w.multiply(sigs.get(i).getSig()
            .modPow(ThreshUtil.lambda(sigs.get(i).getId(), sigs.toArray(new SigShare[getK()]), delta), n));
      }

      w = w.mod(n);
      return w;
    }
  }
}
