package threshsig;

import java.math.BigInteger;
import java.security.MessageDigest;

import static threshsig.ThreshUtil.FOUR;
import static threshsig.ThreshUtil.TWO;

/**
 * A GroupKey with information common to all the keyshares. Generated by the
 * Dealer class
 * 
 * Reference: "Practical Threshold Signatures",<br>
 * Victor Shoup (sho@zurich.ibm.com), IBM Research Paper RZ3121, 4/30/99<BR>
 * 
 * @author Steve Weis <sweis@mit.edu>
 */

// TODO: Investigate the security of reusing the key parameters (q,p) with a
// new Poly, since they are computationally expensive
public class GroupKey {
  /** Whether to test */
  private final static boolean CHECKVERIFIER = true;

  /** (k,l) Parameters. k out of l shares needed for a signature */
  private int k, l;

  /** The exponent of the groupKeyPair */
  private BigInteger e;

  /** The RSA modulus of the groupKeyPair */
  private BigInteger n;

  /** Group Verifier */
  private BigInteger v;

  /** Verifier for each share */
  private BigInteger[] vk;

  public GroupKey(final int k, final int l, final int keysize,
      final BigInteger e, final BigInteger n, final BigInteger v, final BigInteger[] vk) {
    this.k = k;
    this.l = l;
    this.e = e;
    this.n = n;
    this.v = v;
    this.vk = vk;
  }

  /**
   * Returns the minimum threshold size
   * 
   * @return The minimum threshold size for this group 'k'.
   */
  public int getK() {
    return k;
  }

  /**
   * Returns the group size
   * 
   * @return The size of this key's associated group.
   */
  public int getL() {
    return l;
  }

  /**
   * Returns the group key modulus
   * 
   * @return This group's modulus.
   */
  public BigInteger getModulus() {
    return n;
  }

  /**
   * Returns the group key exponent
   * 
   * @return This group's exponent
   */
  public BigInteger getExponent() {
    return e;
  }

  public BigInteger getGroupVerifier() {
    return v;
  }

  public BigInteger getVerifier(int id) {
    return vk[id - 1];
  }

  public boolean verify(final byte[] data, final SigShare[] sigs) throws ThresholdSigException {
    // return SigShare.verify(data, sigs, k, l, n, e, this);

    // Sanity Check - make sure there are at least k unique sigs out of l
    // possible
    final boolean[] haveSig = new boolean[l];
    for (int i = 0; i < k; i++) {
      // debug("Checking sig " + sigs[i].getId());
      if (sigs[i] == null) {
        throw new ThresholdSigException("Null signature");
      }
      if (haveSig[sigs[i].getId() - 1]) {
        throw new ThresholdSigException("Duplicate signature: " + sigs[i].getId());
      }
      haveSig[sigs[i].getId() - 1] = true;
    }

    final BigInteger x = (new BigInteger(data)).mod(n);
    final BigInteger delta = ThreshUtil.factorial(l);

    // Test the verifier of each signature to ensure there are
    // no dummy sigs thrown in to corrupt the batch
    if (CHECKVERIFIER) {
      final BigInteger xtilde = x.modPow(FOUR.multiply(delta), n);

      try {
        final MessageDigest md = MessageDigest.getInstance("SHA-256");

        for (int i = 0; i < k; i++) {
          md.reset();
          final Verifier ver = sigs[i].getSigVerifier();
          final BigInteger v = this.getGroupVerifier();
          final BigInteger vi = this.getVerifier(sigs[i].getId());

          // debug("v :" + v);
          md.update(v.toByteArray());

          // debug("xtilde :" + xtilde);
          md.update(xtilde.toByteArray());

          // debug("vi :" + vi);
          md.update(vi.toByteArray());

          final BigInteger xi = sigs[i].getSig();
          // debug("xi^2 :" + xi.modPow(TWO,n));
          md.update(xi.modPow(TWO, n).toByteArray());

          final BigInteger vz = v.modPow(ver.getZ(), n);

          final BigInteger vinegc = vi.modPow(ver.getC(), n).modInverse(n);
          // debug("v^z*v^-c :" + vz.multiply(vinegc).mod(n));
          md.update(vz.multiply(vinegc).mod(n).toByteArray());

          final BigInteger xtildez = xtilde.modPow(ver.getZ(), n);

          // TODO: CHECK PAPER!
          final BigInteger xineg2c = xi.modPow(ver.getC(), n).modInverse(n);
          // According to Shoup, pg. 8 this should be:
          // xi.modPow(TWO,n).modPow(ver.getC(),n).modInverse(n);

          // Something to do with working in Q_n since every
          // element is a square

          // debug("xi^-2cx: " + xineg2c.multiply(xtildez).mod(n));
          md.update(xineg2c.multiply(xtildez).mod(n).toByteArray());
          final BigInteger result = new BigInteger(md.digest()).mod(n);

          if (!result.equals(ver.getC())) {
            debug("Share verifier " + (sigs[i].getId() - 1) + " is not OK");
            return false;
          }
        }
      } catch (final java.security.NoSuchAlgorithmException ex) {
        debug("Provider could not locate SHA message digest .");
        ex.printStackTrace();
      }
    }

    BigInteger w = BigInteger.valueOf(1l);

    for (int i = 0; i < k; i++) {
      w = w.multiply(sigs[i].getSig().modPow(ThreshUtil.lambda(sigs[i].getId(), sigs, delta), n));
    }

    // eprime = delta^2*4
    final BigInteger eprime = delta.multiply(delta).shiftLeft(2);

    w = w.mod(n);
    final BigInteger xeprime = x.modPow(eprime, n);
    final BigInteger we = w.modPow(e, n);
    return (xeprime.compareTo(we) == 0);
  }

  // Debugging
  // ............................................................................
  private static void debug(final String s) {
    System.err.println("GroupKey: " + s);
  }
}
