package threshsig;

import java.math.BigInteger;
import java.security.MessageDigest;

/**
 * A Secret Key Share for an RSA (k,l) Threshold Scheme
 * 
 * Reference: "Practical Threshold Signatures",<br>
 * Victor Shoup (sho@zurich.ibm.com), IBM Research Paper RZ3121, 4/30/99<BR>
 * 
 * @author Steve Weis <sweis@mit.edu>
 */
public class KeyShare {
  // Constants and variables
  // ............................................................................
  /** Secret key value */
  private BigInteger secret;

  /** The secret key value used to sign messages. Should not be exposed */
  private BigInteger signVal;

  /** groupKey for convenience */
  private GroupKey gk;
  /** From 1 to gk.getL() */
  private int id;

  // Constructors
  // ............................................................................

  /**
   * Create a new share
   * 
   * @param id     - the identifier of this share
   * @param secret - a secret value generated by a Dealer
   * @param n      - the modulo of the group public key
   * @param delta  - l! (group size factorial)
   */
  public KeyShare(final int id, final BigInteger secret, final BigInteger delta) {
    this.id = id;
    this.secret = secret;

    this.signVal = ThreshUtil.FOUR.multiply(delta).multiply(secret);
  }

  public KeyShare(int id, BigInteger secret, GroupKey gk) {
    this(id, secret, gk.getDelta());
    this.gk = gk;
  }

  // Public Methods
  // ............................................................................

  public int getId() {
    return id;
  }

  public BigInteger getSecret() {
    return secret;
  }

  public void setGroupKey(final GroupKey gk) {
    this.gk = gk;
  }

  public BigInteger getSignVal() {
    return this.signVal;
  }

  @Override
  public String toString() {
    return "KeyShare[" + id + "]";
  }

  /**
   * Create a SigShare and a Verifier for byte[] b<BR>
   * 
   * Refer to Shoup pg. 8 <BR>
   * 
   * @param b The array of bytes to produce a signature share for.
   * @return a sig share with a verifier
   */
  public SigShare sign(final byte[] b) {
    final BigInteger x = (new BigInteger(b)).mod(gk.getModulus());

    final int randbits = gk.getModulus().bitLength() + 3 * ThreshUtil.L1;

    // r \elt (0, 2^L(n)+3*l1)
    final BigInteger r = (new BigInteger(randbits, ThreshUtil.getRandom()));
    final BigInteger vprime = gk.getGroupVerifier().modPow(r, gk.getModulus());
    final BigInteger xtilde = x.modPow(ThreshUtil.FOUR.multiply(gk.getDelta()), gk.getModulus());
    final BigInteger xprime = xtilde.modPow(r, gk.getModulus());

    BigInteger c = null;
    BigInteger z = null;
    // Try to generate C and Z
    try {
      MessageDigest md = MessageDigest.getInstance(ThreshUtil.DIGEST_ALGO);
      md.reset();

      // debug("v: " + groupVerifier.mod(n));
      md.update(gk.getGroupVerifier().toByteArray());

      // debug("xtilde: " + xtilde);
      md.update(xtilde.toByteArray());

      // debug("vi: " + verifier.mod(n));
      md.update(gk.getVerifier(id).toByteArray());

      // debug("xi^2: " + x.modPow(signVal,n).modPow(TWO,n));
      md.update(x.modPow(signVal, gk.getModulus()).modPow(ThreshUtil.TWO, gk.getModulus()).toByteArray());

      // debug("v': "+ vprime);
      md.update(vprime.toByteArray());

      // debug("x': " + xprime);
      md.update(xprime.toByteArray());
      c = new BigInteger(md.digest()).mod(gk.getModulus());
      z = (c.multiply(secret)).add(r);
    } catch (final java.security.NoSuchAlgorithmException e) {
      debug("Provider could not locate SHA message digest .");
      e.printStackTrace();
    }

    final Verifier ver = new Verifier(z, c);

    return new SigShare(id, x.modPow(signVal, gk.getModulus()), ver);
  }

  // Debugging
  // ............................................................................
  private static void debug(final String s) {
    System.err.println("KeyShare: " + s);
  }
}
